/// Flutter icons CustomIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  IconData linux = const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData github = const IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData windows = const IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
